name: Test and build

on:
  pull_request:
    branches: [ master ]

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configurar Node y ejecutar pruebas
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Iniciar Proyecto Node
        run: npm init -y

      - name: Instalar Jest
        run: npm install --save-dev jest

      - name: Ejecutar Pruebas
        run: npm run test

      - name: Subir reporte
        uses: actions/upload-artifact@v2
        with:
          name: Jest Coverage
          path: coverage/

  build-push:
    needs: unit-testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login a Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.EDSON_DOCKERHUB_ID }}
          password: ${{ secrets.EDSON_DOCKERHUB_TOKEN }}

      - name: Configurar QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configurar buildx
        uses: docker/setup-buildx-action@v1

      - name: Construir con buildx
        run: |
          docker buildx build \
          --push \
          --tag amigosinformaticos/api_gourmet_race:latest \
          --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 .