# This is a basic workflow to help you get started with Actions

name: CI en PWA

# Controls when the action will run. 
on:
  # Triggers
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Configurar Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar Jest
        run: npm install --save-dev jest

      - name: Ejecutar pruebas con reporte
        run: jest --coverage

      - name: Subir reporte
        uses: actions/upload-artifac@v2
        with:
          name: Jest Coverage
          path: coverage/